### ISSUE TITLE
Run FSL's testing suite when submitting a PR?

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults#14]
Check if whenever we create a new PR in this repo we could run the FSL's exporter tests to check that both modules are still compatible.

**Comment by chrisfilo** [comment]
This could be done on circle ci or Travis automatically.

**Comment by cmaumet** [comment]
Thanks @chrisfilo! I was thinking Travis as that's what we are using in the other repo (I have no experience with circle ci). But, we will need to wait until our test data is available online (work in progress).

**Comment by cmaumet** [comment]
Testing is done from the FSL exporter.
